[files]

[files.example1]
template = "./test/example1/.env.sample"
output = "./test/example1/.env"
allow-empty = ["IGNORED_ENV"]

[files.example2]
template = "./test/example2/.env.local.sample"
output = "./test/example2/.env.local"